### ISSUE TITLE
Item creation and basic interaction

### ISSUE THREAD

**Issue by OliverLSanz** [OliverLSanz/sandbox_mud#1]
# User Story
"As a room creator, I want to create items so that I can make my rooms more detailed and interactive"

# Tasks
- [x] Define item's data model.
- [x] Update existing data models to handle items.
- [x] Update look verb to show items in room.
- [x] Update look verb so that it can also yield items' descriptions.
- [x] Implement verb for creating new items.
- [x] Implement verb for modifying existing items.

**Comment by OliverLSanz** [comment]
# User Story
"As a room creator, I want to create items so that I can make my rooms more detailed and interactive"

# Tasks
- [] Define item's data model.
- [] Update existing data models to handle items.
- [] Update look verb to show items in room.
- [] Update look verb so that it can also yield items' descriptions.
- [] Implement verb for creating new items.
- [] Implement verb for modifying existing items.
- [] Implement verb for deleting existing items.

**Comment by OliverLSanz** [comment]
Done
