### ISSUE TITLE
Code is getting messy after milestone 1

### ISSUE THREAD

**Issue by OliverLSanz** [OliverLSanz/sandbox_mud#43]
We should make it lean and perfect before diving into bigger features.

**Comment by OliverLSanz** [comment]
Lets check for:

- [ ] Duplicated code at verbs that could be extracted to a function in the utils module.
- [ ] Manual entities handling that should be done via an entity method.
- [ ] Objects handling things that are out of their responsibility scope.
- [ ] Code that needs documenting.
- [ ] Code that needs cleaning.

**Comment by OliverLSanz** [comment]
All code has been revised and while it isn't perfect yet, imperfections are well contained and won't affect other parts of the code. Lets keep moving!
